### ISSUE TITLE
Crash on bootstrap node

### ISSUE THREAD

**Issue by HM4704** [lunfardo314/proxima#6]
The following crash occured on boostrap node:

07-13 18:34:32.027	INFO	vertices deleted: 0, detached past cones: 0. Vertices left: 177. Cached state readers purged: 0, left: 4. Mem. alloc: 308.7 MB, GC: 19, GoRt: 112, 
07-13 18:34:32.545	INFO	uptime: 14m56s, allocated memory: 309.0 MB, Goroutines: 19, GC counter: 112
07-13 18:34:34.013	INFO	-- ATTACH BRANCH (boot.b0 15736/31895) [16305|0br]865404..(in 2/out 2), ci=1_528_305/bi=442_424, base: [16304|0br]2739a0.., cov: 80_437_119_946_292, slot inflation: 2_051_166, supply: 1_000_224_736_758_410
07-13 18:34:34.325	INFO	[boot-$/af7bed..]	purged 1 own milestones
07-13 18:34:34.506	INFO	-- ATTACH SEQ TX (boot.b0 15736/31896) [16305|5sq]ca8fb1..(in 1/out 1), ci=1_608_742/bi=0, base: [16305|0br]865404.., cov: 80_437_127_226_282, slot inflation: 1_608_742
07-13 18:34:34.507	FATAL	assertion failed:: NewIncrementalAttacher: target is closer than allowed pace (1): 16305|5 -> 16305|5
github.com/lunfardo314/proxima/global.(*Global).Assertf
	/home/pi/Projects/crypto/proxima/proxima/global/global.go:196
github.com/lunfardo314/proxima/core/attacher.NewIncrementalAttacher
	/home/pi/Projects/crypto/proxima/proxima/core/attacher/attacher_incremental.go:22
github.com/lunfardo314/proxima/sequencer/factory/proposer_base.(*BaseProposer).propose
	/home/pi/Projects/crypto/proxima/proxima/sequencer/factory/proposer_base/proposer_base.go:56
github.com/lunfardo314/proxima/sequencer/factory.init.0.Strategy.func1.1
	/home/pi/Projects/crypto/proxima/proxima/sequencer/factory/proposer_base/proposer_base.go:28
github.com/lunfardo314/proxima/sequencer/factory/proposer_generic.(*TaskGeneric).Run
	/home/pi/Projects/crypto/proxima/proxima/sequencer/factory/proposer_generic/proposer_generic.go:99
github.com/lunfardo314/proxima/sequencer/factory.(*MilestoneFactory).startProposerWorkers.func1
	/home/pi/Projects/crypto/proxima/proxima/sequencer/factory/factory.go:273
github.com/lunfardo314/proxima/util.RunWrappedRoutine.func1.1
	/home/pi/Projects/crypto/proxima/proxima/util/util_panic.go:37
github.com/lunfardo314/proxima/util.CatchPanicOrError.func1
	/home/pi/Projects/crypto/proxima/proxima/util/util_panic.go:26
github.com/lunfardo314/proxima/util.CatchPanicOrError
	/home/pi/Projects/crypto/proxima/proxima/util/util_panic.go:27
github.com/lunfardo314/proxima/util.RunWrappedRoutine.func1
	/home/pi/Projects/crypto/proxima/proxima/util/util_panic.go:36

**Comment by HM4704** [comment]
The crash occured with a 2 node setup with a Raspi 4 as bootstrap node. The second node could have been restarted during the crash because I worked with it, but I cannot tell for sure. I saw this crash only once during the last days of testing up to now.

**Comment by lunfardo314** [comment]
base proposer in the sequencer was still trying to propose for the target time while milestone already submitted -> resulted in failed assertion about validity of the target time pace. 
Fixed by abandoning proposer immediately in commit eb0d0945f20bd2699a9e3ce9294cf6a90313dfe3
